/* Image sources:
   PRIMARY — imagin.studio: commercial automotive imaging API (AutoTrader, CarWow, OEM configurators).
     Sign up at https://www.imagin.studio/solution/car-image-api for a production customer ID.
     Replace IMAGIN_STUDIO_CUSTOMER below with your licensed ID before going live.
   FALLBACK — pressImageUrl: Wikimedia Commons CC-BY-SA images for models imagin.studio
     does not cover (mainly India-specific Tata / Mahindra / MG variants).
     Attribution required per CC-BY-SA 4.0: "© Wikimedia Commons contributors / CC BY-SA 4.0"
   imageVerified=true  → imagin.studio render confirmed against Indian-market model+year.
   imageVerified=false → imagin.studio coverage uncertain; pressImageUrl provides CC fallback. */

/* ── PRODUCTION CONFIG ───────────────────────────────────────────
   Replace 'img' with your licensed imagin.studio customer ID.
   'img' is the public demo key — rate-limited and not for production use. */
const IMAGIN_STUDIO_CUSTOMER = 'img';

function imgStudio(make, modelFamily, year) {
  return `https://cdn.imagin.studio/getimage?customer=${IMAGIN_STUDIO_CUSTOMER}&make=${encodeURIComponent(make)}&modelFamily=${encodeURIComponent(modelFamily)}&modelYear=${year}&angle=side-34&width=640&paintId=default`;
}

/* Wikimedia Commons stable redirect — no hash path needed, resolves to CDN automatically. */
function wikiImg(filename) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(filename)}?width=640`;
}

const CAR_DATABASE = [
  /* ── HATCHBACKS ─────────────────────────────────────────── */
  {
    id:1, make:"Maruti", model:"Alto K10", year:2024, variant:"VXi AGS",
    price:480000, category:"Hatchback", fuel:"Petrol", transmission:"AMT",
    mileage:24.9, engine:"1.0L K-Series Dual Jet", power:"67 hp", torque:"89 Nm",
    seats:5, color:"Silky Silver", rating:4.0, reviews:520,
    features:["SmartPlay Studio 7\"","Rear Parking Sensor","Keyless Entry","Dual Airbags"],
    pros:["Highest mileage in class","Ultra affordable","Easy to park"],
    cons:["Basic safety","Small cabin","No airbags in base"],
    safetyRating:3, depreciationRate:18, maintenanceCostPerYear:12000,
    insuranceCostPerYear:22000, totalCostOfOwnership5yr:1200000,
    analyticsScore:72, marketTrend:"stable", demandIndex:88,
    tag:"Entry Level",
    image:imgStudio("suzuki","alto-k10",2024), imageVerified:true
  },
  {
    id:2, make:"Maruti", model:"WagonR", year:2024, variant:"ZXi+ AMT",
    price:690000, category:"Hatchback", fuel:"Petrol", transmission:"AMT",
    mileage:23.56, engine:"1.2L K12N Dual Jet", power:"90 hp", torque:"113 Nm",
    seats:5, color:"Prime Glistening Grey", rating:4.2, reviews:680,
    features:["SmartPlay Pro 9\"","Auto AC","Rear Camera","6 Airbags","Wireless Charging"],
    pros:["Tallboy design","Best-in-segment space","Reliable"],
    cons:["Boxy styling","Firm ride"],
    safetyRating:4, depreciationRate:14, maintenanceCostPerYear:15000,
    insuranceCostPerYear:28000, totalCostOfOwnership5yr:1500000,
    analyticsScore:78, marketTrend:"stable", demandIndex:91,
    tag:"Family Fav",
    image:imgStudio("suzuki","wagon-r",2024), imageVerified:true
  },
  {
    id:3, make:"Maruti", model:"Swift", year:2024, variant:"ZXi+ AMT",
    price:910000, category:"Hatchback", fuel:"Petrol", transmission:"AMT",
    mileage:25.75, engine:"1.2L Z12E Dual Jet", power:"82 hp", torque:"112 Nm",
    seats:5, color:"Magma Grey", rating:4.4, reviews:750,
    features:["9\" Touchscreen","HUD","360 Camera","6 Airbags","ESP","Wireless Charging"],
    pros:["Sporty looks","Class-best mileage","Fun to drive"],
    cons:["Stiff suspension","Small boot"],
    safetyRating:4, depreciationRate:12, maintenanceCostPerYear:18000,
    insuranceCostPerYear:34000, totalCostOfOwnership5yr:1700000,
    analyticsScore:84, marketTrend:"rising", demandIndex:94,
    tag:"Best Seller",
    image:imgStudio("suzuki","swift",2024), imageVerified:true
  },
  {
    id:4, make:"Maruti", model:"Baleno", year:2024, variant:"Alpha CVT",
    price:920000, category:"Hatchback", fuel:"Petrol", transmission:"CVT",
    mileage:22.9, engine:"1.2L DualJet VVT", power:"90 hp", torque:"113 Nm",
    seats:5, color:"Grandeur Grey", rating:4.2, reviews:412,
    features:["HUD","360 Camera","Arkamys Audio","SmartPlay Pro 9\"","Wireless Charging"],
    pros:["Best-in-class mileage","Premium feel","Wireless charging"],
    cons:["Average safety rating","CVT lag"],
    safetyRating:3, depreciationRate:10, maintenanceCostPerYear:18000,
    insuranceCostPerYear:32000, totalCostOfOwnership5yr:1600000,
    analyticsScore:79, marketTrend:"stable", demandIndex:88,
    tag:"Budget King",
    image:imgStudio("suzuki","baleno",2024), imageVerified:true
  },
  {
    id:5, make:"Maruti", model:"Ignis", year:2024, variant:"Alpha MT",
    price:870000, category:"Hatchback", fuel:"Petrol", transmission:"Manual",
    mileage:20.89, engine:"1.2L K12N Dual Jet", power:"90 hp", torque:"113 Nm",
    seats:5, color:"Nexa Blue", rating:4.1, reviews:210,
    features:["SmartPlay Pro","LED DRLs","Rear Camera","Wireless Charging","Auto AC"],
    pros:["Unique design","Compact urban car","Decent features"],
    cons:["No automatic in top trim","Tight rear space"],
    safetyRating:3, depreciationRate:16, maintenanceCostPerYear:17000,
    insuranceCostPerYear:30000, totalCostOfOwnership5yr:1550000,
    analyticsScore:71, marketTrend:"stable", demandIndex:65,
    tag:"Urban Niche",
    image:imgStudio("suzuki","ignis",2024), imageVerified:true
  },
  {
    id:6, make:"Hyundai", model:"Grand i10 Nios", year:2024, variant:"Sportz AMT",
    price:750000, category:"Hatchback", fuel:"Petrol", transmission:"AMT",
    mileage:20.7, engine:"1.2L Kappa VTVT", power:"83 hp", torque:"114 Nm",
    seats:5, color:"Typhoon Silver", rating:4.1, reviews:390,
    features:["8\" Touchscreen","Wireless Charging","Rear Camera","Bluelink Connected","6 Airbags"],
    pros:["Premium interior","Good features for price","Smooth ride"],
    cons:["Small boot","Basic safety in lower trims"],
    safetyRating:3, depreciationRate:15, maintenanceCostPerYear:16000,
    insuranceCostPerYear:28000, totalCostOfOwnership5yr:1500000,
    analyticsScore:75, marketTrend:"stable", demandIndex:80,
    tag:"Smart Value",
    image:imgStudio("hyundai","grand-i10",2024), imageVerified:true
  },
  {
    id:7, make:"Hyundai", model:"i20", year:2024, variant:"Asta (O) Turbo DCT",
    price:1250000, category:"Hatchback", fuel:"Petrol", transmission:"DCT",
    mileage:18.0, engine:"1.0L T-GDi Turbo", power:"120 hp", torque:"172 Nm",
    seats:5, color:"Atlas White", rating:4.5, reviews:480,
    features:["10.25\" Touchscreen","Bose Audio","Sunroof","ADAS","Ventilated Seats","Bluelink"],
    pros:["Premium hatchback","Turbo punch","Feature loaded"],
    cons:["Expensive top variant","Small back seat"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:28000,
    insuranceCostPerYear:48000, totalCostOfOwnership5yr:2200000,
    analyticsScore:87, marketTrend:"rising", demandIndex:86,
    tag:"Premium Hatch",
    image:imgStudio("hyundai","i20",2024), imageVerified:true
  },
  {
    id:8, make:"Tata", model:"Tiago", year:2024, variant:"XZA+ AMT",
    price:750000, category:"Hatchback", fuel:"Petrol", transmission:"AMT",
    mileage:19.8, engine:"1.2L Revotron Turbo", power:"86 hp", torque:"113 Nm",
    seats:5, color:"Daytona Grey", rating:4.0, reviews:310,
    features:["7\" Touchscreen","Rear Camera","iRA Connected","Auto AC","6 Airbags"],
    pros:["5-star GNCAP safety","Solid build","Value for money"],
    cons:["Basic interior","CVT not available"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:18000,
    insuranceCostPerYear:30000, totalCostOfOwnership5yr:1550000,
    analyticsScore:76, marketTrend:"rising", demandIndex:82,
    tag:"Safety Star",
    image:imgStudio("tata","tiago",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Tiago_facelift_2024.jpg")
  },
  {
    id:9, make:"Tata", model:"Altroz", year:2024, variant:"XZ+ DCA",
    price:1050000, category:"Hatchback", fuel:"Petrol", transmission:"DCA",
    mileage:18.1, engine:"1.2L iTurbo", power:"110 hp", torque:"140 Nm",
    seats:5, color:"Avenue White", rating:4.3, reviews:240,
    features:["10.25\" Touchscreen","Sunroof","6 Airbags","iRA Connected","Ventilated Seats"],
    pros:["5-star GNCAP safety","Premium build","Turbo option"],
    cons:["DCA can be jerky","Small boot"],
    safetyRating:5, depreciationRate:14, maintenanceCostPerYear:22000,
    insuranceCostPerYear:40000, totalCostOfOwnership5yr:1900000,
    analyticsScore:81, marketTrend:"rising", demandIndex:78,
    tag:"Safe Hatch",
    image:imgStudio("tata","altroz",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Altroz_2024.jpg")
  },
  {
    id:10, make:"Renault", model:"Kwid", year:2024, variant:"RXL AMT",
    price:490000, category:"Hatchback", fuel:"Petrol", transmission:"AMT",
    mileage:22.5, engine:"1.0L SCe", power:"68 hp", torque:"91 Nm",
    seats:5, color:"Fiery Red", rating:3.9, reviews:290,
    features:["8\" MediaNAV","Rear Camera","Keyless Entry","Speed Alert System"],
    pros:["SUV-like stance","Affordable","Good mileage"],
    cons:["Basic safety","Cramped rear","Noisy cabin"],
    safetyRating:2, depreciationRate:20, maintenanceCostPerYear:14000,
    insuranceCostPerYear:20000, totalCostOfOwnership5yr:1200000,
    analyticsScore:63, marketTrend:"falling", demandIndex:58,
    tag:"Budget Entry",
    image:imgStudio("renault","kwid",2024), imageVerified:true
  },
  {
    id:11, make:"Volkswagen", model:"Polo", year:2022, variant:"Highline Plus",
    price:1050000, category:"Hatchback", fuel:"Petrol", transmission:"Manual",
    mileage:17.4, engine:"1.0L TSI", power:"110 hp", torque:"175 Nm",
    seats:5, color:"Deep Black", rating:4.4, reviews:185, discontinued:true,
    features:["Composition Media","Traction Control","6 Airbags","LED DRLs"],
    pros:["European build quality","Peppy 1.0 TSI","Fun to drive"],
    cons:["Discontinued in India (Jul 2022)","Expensive parts","Limited service"],
    safetyRating:4, depreciationRate:22, maintenanceCostPerYear:38000,
    insuranceCostPerYear:42000, totalCostOfOwnership5yr:2200000,
    analyticsScore:65, marketTrend:"falling", demandIndex:22,
    tag:"Discontinued",
    image:imgStudio("volkswagen","polo",2022), imageVerified:true
  },
  {
    id:12, make:"Toyota", model:"Glanza", year:2024, variant:"V CVT",
    price:890000, category:"Hatchback", fuel:"Petrol", transmission:"CVT",
    mileage:22.9, engine:"1.2L DualJet VVT", power:"90 hp", torque:"113 Nm",
    seats:5, color:"Cafe White", rating:4.2, reviews:170,
    features:["SmartPlay Pro 9\"","HUD","360 Camera","6 Airbags","Wireless Charging"],
    pros:["Toyota reliability","Wide service network","Same platform as Baleno"],
    cons:["Badge premium over Baleno","Slightly higher price"],
    safetyRating:3, depreciationRate:11, maintenanceCostPerYear:17000,
    insuranceCostPerYear:33000, totalCostOfOwnership5yr:1620000,
    analyticsScore:78, marketTrend:"stable", demandIndex:72,
    tag:"Toyota Trust",
    image:imgStudio("toyota","glanza",2024), imageVerified:true
  },
  {
    id:13, make:"Citroen", model:"C3", year:2024, variant:"MAX Turbo",
    price:890000, category:"Hatchback", fuel:"Petrol", transmission:"Manual",
    mileage:19.8, engine:"1.2L PureTech Turbo", power:"110 hp", torque:"190 Nm",
    seats:5, color:"Elixir Red", rating:4.0, reviews:98,
    features:["10\" Touchscreen","LED Headlamps","Wireless Charging","6 Airbags"],
    pros:["Unique European styling","Turbo performance","Comfortable ride"],
    cons:["Limited service network","Small boot"],
    safetyRating:3, depreciationRate:18, maintenanceCostPerYear:28000,
    insuranceCostPerYear:35000, totalCostOfOwnership5yr:1700000,
    analyticsScore:70, marketTrend:"stable", demandIndex:55,
    tag:"Euro Style",
    image:imgStudio("citroen","c3",2024), imageVerified:true
  },

  /* ── SEDANS ─────────────────────────────────────────────── */
  {
    id:14, make:"Maruti", model:"Dzire", year:2024, variant:"ZXi+ AMT",
    price:1000000, category:"Sedan", fuel:"Petrol", transmission:"AMT",
    mileage:25.71, engine:"1.2L Z12E Dual Jet", power:"82 hp", torque:"112 Nm",
    seats:5, color:"Splendid Silver", rating:4.3, reviews:580,
    features:["SmartPlay Pro","HUD","360 Camera","6 Airbags","Wireless Charging"],
    pros:["#1 selling sedan","Incredible mileage","Low maintenance"],
    cons:["Compact boot","AMT can jerk in traffic"],
    safetyRating:4, depreciationRate:11, maintenanceCostPerYear:16000,
    insuranceCostPerYear:35000, totalCostOfOwnership5yr:1750000,
    analyticsScore:82, marketTrend:"stable", demandIndex:93,
    tag:"Segment Leader",
    image:imgStudio("suzuki","dzire",2024), imageVerified:true
  },
  {
    id:15, make:"Honda", model:"Amaze", year:2024, variant:"V CVT",
    price:970000, category:"Sedan", fuel:"Petrol", transmission:"CVT",
    mileage:19.7, engine:"1.2L i-VTEC SOHC", power:"90 hp", torque:"110 Nm",
    seats:5, color:"Radiant Red", rating:4.1, reviews:310,
    features:["7\" Touchscreen","Honda Connect","Rear Camera","6 Airbags","Lane Watch"],
    pros:["Reliable Honda engine","Smooth CVT","Spacious boot 420L"],
    cons:["Outdated design","Firm suspension"],
    safetyRating:4, depreciationRate:14, maintenanceCostPerYear:22000,
    insuranceCostPerYear:36000, totalCostOfOwnership5yr:1800000,
    analyticsScore:74, marketTrend:"stable", demandIndex:70,
    tag:"Reliable Pick",
    image:imgStudio("honda","amaze",2024), imageVerified:true
  },
  {
    id:16, make:"Honda", model:"City", year:2024, variant:"ZX CVT",
    price:1650000, category:"Sedan", fuel:"Petrol", transmission:"CVT",
    mileage:18.4, engine:"1.5L i-VTEC DOHC", power:"119 hp", torque:"145 Nm",
    seats:5, color:"Lunar Silver", rating:4.3, reviews:215,
    features:["Honda Sensing ADAS","LED Headlamps","8\" Touchscreen","Wireless Charging","Lane Watch"],
    pros:["Excellent fuel economy","Spacious cabin","Reliable"],
    cons:["Soft suspension","Boot could be bigger"],
    safetyRating:4, depreciationRate:15, maintenanceCostPerYear:28000,
    insuranceCostPerYear:55000, totalCostOfOwnership5yr:2600000,
    analyticsScore:82, marketTrend:"stable", demandIndex:85,
    tag:"Value Pick",
    image:imgStudio("honda","city",2024), imageVerified:true
  },
  {
    id:17, make:"Hyundai", model:"Aura", year:2024, variant:"SX AMT",
    price:1000000, category:"Sedan", fuel:"Petrol", transmission:"AMT",
    mileage:20.5, engine:"1.2L Kappa VTVT", power:"83 hp", torque:"114 Nm",
    seats:5, color:"Polar White", rating:4.0, reviews:195,
    features:["8\" Touchscreen","Wireless Charging","Bluelink","Rear Camera","6 Airbags"],
    pros:["Connected tech","Stylish design","Good boot space"],
    cons:["AMT can jerk","Average highway manners"],
    safetyRating:3, depreciationRate:15, maintenanceCostPerYear:20000,
    insuranceCostPerYear:36000, totalCostOfOwnership5yr:1800000,
    analyticsScore:73, marketTrend:"stable", demandIndex:72,
    tag:"Connected Sedan",
    image:imgStudio("hyundai","aura",2024), imageVerified:true
  },
  {
    id:18, make:"Hyundai", model:"Verna", year:2024, variant:"SX(O) Turbo DCT",
    price:1850000, category:"Sedan", fuel:"Petrol", transmission:"DCT",
    mileage:17.2, engine:"1.5L Turbo GDi", power:"160 hp", torque:"253 Nm",
    seats:5, color:"Abyss Black", rating:4.6, reviews:320,
    features:["10.25\" Touchscreen","ADAS Level 2","Panoramic Sunroof","Bose Audio","BLUELINK","Ventilated Seats"],
    pros:["Most powerful in class","Feature-loaded","5-star safety"],
    cons:["Expensive top variant","Stiff ride"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:35000,
    insuranceCostPerYear:65000, totalCostOfOwnership5yr:2900000,
    analyticsScore:90, marketTrend:"rising", demandIndex:89,
    tag:"Segment King",
    image:imgStudio("hyundai","verna",2024), imageVerified:true
  },
  {
    id:19, make:"Skoda", model:"Slavia", year:2024, variant:"Style 1.5 TSI DSG",
    price:1890000, category:"Sedan", fuel:"Petrol", transmission:"DSG",
    mileage:16.1, engine:"1.5L TSI EVO ACT", power:"150 hp", torque:"250 Nm",
    seats:5, color:"Brilliant Silver", rating:4.5, reviews:175,
    features:["10\" Virtual Cockpit","Canton Audio","Sunroof","6 Airbags","ESC","Wireless Charging"],
    pros:["European driving dynamics","Large boot 521L","DSG smooth"],
    cons:["High service cost","Limited dealerships"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:45000,
    insuranceCostPerYear:68000, totalCostOfOwnership5yr:3100000,
    analyticsScore:86, marketTrend:"stable", demandIndex:68,
    tag:"Euro Sedan",
    image:imgStudio("skoda","slavia",2024), imageVerified:true
  },
  {
    id:20, make:"Volkswagen", model:"Virtus", year:2024, variant:"GT Plus DSG",
    price:1850000, category:"Sedan", fuel:"Petrol", transmission:"DSG",
    mileage:16.35, engine:"1.5L TSI EVO ACT", power:"150 hp", torque:"250 Nm",
    seats:5, color:"Curcuma Yellow", rating:4.4, reviews:160,
    features:["10\" Touchscreen","Wireless Charging","Sunroof","6 Airbags","VW Play App"],
    pros:["Best performance sedan","Huge boot 521L","Build quality"],
    cons:["Expensive service","Limited network"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:45000,
    insuranceCostPerYear:68000, totalCostOfOwnership5yr:3100000,
    analyticsScore:85, marketTrend:"stable", demandIndex:66,
    tag:"GT Performance",
    image:imgStudio("volkswagen","virtus",2024), imageVerified:true
  },
  {
    id:21, make:"Toyota", model:"Camry", year:2024, variant:"Hybrid",
    price:4800000, category:"Sedan", fuel:"Hybrid", transmission:"e-CVT",
    mileage:23.27, engine:"2.5L TNGA Hybrid", power:"218 hp combined", torque:"221 Nm",
    seats:5, color:"Platinum White Pearl", rating:4.7, reviews:95,
    features:["JBL Premium Audio","10\" Digital Cluster","HUD","360 Camera","Toyota Safety Sense"],
    pros:["Exceptional mileage for size","Bulletproof reliability","Hybrid savings"],
    cons:["Expensive price","Limited dealer network"],
    safetyRating:5, depreciationRate:12, maintenanceCostPerYear:65000,
    insuranceCostPerYear:140000, totalCostOfOwnership5yr:6800000,
    analyticsScore:88, marketTrend:"rising", demandIndex:60,
    tag:"Hybrid Leader",
    image:imgStudio("toyota","camry",2024), imageVerified:true
  },
  {
    id:22, make:"Skoda", model:"Octavia", year:2024, variant:"Laurin & Klement",
    price:3690000, category:"Sedan", fuel:"Petrol", transmission:"DSG",
    mileage:14.5, engine:"2.0L TSI 4-cylinder", power:"190 hp", torque:"320 Nm",
    seats:5, color:"Graphite Grey", rating:4.6, reviews:88,
    features:["Canton Audio","Panoramic Sunroof","Virtual Cockpit Plus","Ambient Lighting","Matrix LED"],
    pros:["Premium feel at lower price","Huge boot 600L","Great highway car"],
    cons:["High service cost","Niche appeal"],
    safetyRating:5, depreciationRate:17, maintenanceCostPerYear:70000,
    insuranceCostPerYear:120000, totalCostOfOwnership5yr:5500000,
    analyticsScore:84, marketTrend:"stable", demandIndex:45,
    tag:"Euro Premium",
    image:imgStudio("skoda","octavia",2024), imageVerified:true
  },
  {
    id:23, make:"Tata", model:"Tigor", year:2024, variant:"XZA+ AMT",
    price:850000, category:"Sedan", fuel:"Petrol", transmission:"AMT",
    mileage:19.55, engine:"1.2L Revotron", power:"86 hp", torque:"113 Nm",
    seats:5, color:"Daytona Grey", rating:3.9, reviews:180,
    features:["7\" Touchscreen","Rear Camera","iRA Connected","6 Airbags","Reverse Park Camera"],
    pros:["5-star GNCAP safety","Affordable sedan","Tata reliability"],
    cons:["Dated design","Small boot"],
    safetyRating:5, depreciationRate:17, maintenanceCostPerYear:18000,
    insuranceCostPerYear:30000, totalCostOfOwnership5yr:1600000,
    analyticsScore:70, marketTrend:"stable", demandIndex:62,
    tag:"Safe Sedan",
    image:imgStudio("tata","tigor",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Tigor_facelift.jpg")
  },

  /* ── COMPACT SUVs ────────────────────────────────────────── */
  {
    id:24, make:"Maruti", model:"Brezza", year:2024, variant:"ZXi+ AT",
    price:1410000, category:"Compact SUV", fuel:"Petrol", transmission:"AT",
    mileage:19.8, engine:"1.5L K15C mild-hybrid", power:"103 hp", torque:"137 Nm",
    seats:5, color:"Brave Khaki", rating:4.3, reviews:540,
    features:["SmartPlay Pro","HUD","360 Camera","6 Airbags","Wireless Charging","Sunroof"],
    pros:["Mild-hybrid efficiency","Segment leader","Low TCO"],
    cons:["Less power vs rivals","Basic infotainment"],
    safetyRating:4, depreciationRate:11, maintenanceCostPerYear:20000,
    insuranceCostPerYear:48000, totalCostOfOwnership5yr:2350000,
    analyticsScore:83, marketTrend:"stable", demandIndex:92,
    tag:"Value SUV",
    image:imgStudio("suzuki","brezza",2024), imageVerified:true
  },
  {
    id:25, make:"Hyundai", model:"Venue", year:2024, variant:"SX(O) Turbo DCT",
    price:1480000, category:"Compact SUV", fuel:"Petrol", transmission:"DCT",
    mileage:18.15, engine:"1.0L T-GDi Turbo", power:"120 hp", torque:"172 Nm",
    seats:5, color:"Ranger Khaki", rating:4.4, reviews:420,
    features:["8\" Touchscreen","ADAS","Sunroof","BlueLink","Air Purifier","6 Airbags"],
    pros:["Turbo performance","ADAS in compact","Connected features"],
    cons:["Cramped rear","Premium priced"],
    safetyRating:4, depreciationRate:13, maintenanceCostPerYear:28000,
    insuranceCostPerYear:52000, totalCostOfOwnership5yr:2500000,
    analyticsScore:84, marketTrend:"rising", demandIndex:85,
    tag:"Smart Compact",
    image:imgStudio("hyundai","venue",2024), imageVerified:true
  },
  {
    id:26, make:"Kia", model:"Sonet", year:2024, variant:"HTX+ Turbo DCT",
    price:1560000, category:"Compact SUV", fuel:"Petrol", transmission:"DCT",
    mileage:18.3, engine:"1.0L T-GDi Turbo", power:"120 hp", torque:"172 Nm",
    seats:5, color:"Gravity Grey", rating:4.4, reviews:380,
    features:["10.25\" Touchscreen","Bose Audio","Sunroof","UVO Connected","6 Airbags"],
    pros:["Bold design","Feature-rich","Peppy turbo"],
    cons:["Cramped rear","Premium price tag"],
    safetyRating:4, depreciationRate:13, maintenanceCostPerYear:30000,
    insuranceCostPerYear:56000, totalCostOfOwnership5yr:2600000,
    analyticsScore:85, marketTrend:"rising", demandIndex:82,
    tag:"Style Compact",
    image:imgStudio("kia","sonet",2024), imageVerified:true
  },
  {
    id:27, make:"Tata", model:"Nexon", year:2024, variant:"Creative+ S AMT",
    price:1500000, category:"Compact SUV", fuel:"Petrol", transmission:"AMT",
    mileage:17.44, engine:"1.2L iTurbo", power:"120 hp", torque:"170 Nm",
    seats:5, color:"Flame Red", rating:4.5, reviews:620,
    features:["10.25\" Touchscreen","ADAS","Sunroof","6 Airbags","iRA Connected","Ventilated Seats"],
    pros:["5-star GNCAP safety","Best-in-class safety score","Feature rich"],
    cons:["AMT can be laggy","Fuel economy trails rivals"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:28000,
    insuranceCostPerYear:52000, totalCostOfOwnership5yr:2500000,
    analyticsScore:88, marketTrend:"rising", demandIndex:94,
    tag:"Safety King",
    image:imgStudio("tata","nexon",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Nexon_facelift_2023.jpg")
  },
  {
    id:28, make:"Tata", model:"Punch", year:2024, variant:"Accomplished+ AMT",
    price:1000000, category:"Compact SUV", fuel:"Petrol", transmission:"AMT",
    mileage:18.82, engine:"1.2L Revotron", power:"86 hp", torque:"113 Nm",
    seats:5, color:"Tropical Mist", rating:4.4, reviews:510,
    features:["7\" Touchscreen","6 Airbags","iRA Connected","Rear Camera","Auto AC"],
    pros:["5-star GNCAP safety","SUV stance","Affordable"],
    cons:["Underpowered","No diesel option"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:20000,
    insuranceCostPerYear:36000, totalCostOfOwnership5yr:1900000,
    analyticsScore:82, marketTrend:"rising", demandIndex:88,
    tag:"Micro SUV Star",
    image:imgStudio("tata","punch",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Punch_2024.jpg")
  },
  {
    id:29, make:"Nissan", model:"Magnite", year:2024, variant:"Tekna+ Turbo CVT",
    price:1250000, category:"Compact SUV", fuel:"Petrol", transmission:"CVT",
    mileage:17.4, engine:"1.0L HRA0 Turbo", power:"100 hp", torque:"160 Nm",
    seats:5, color:"Blade Silver", rating:4.1, reviews:210,
    features:["8\" Touchscreen","360 Camera","Sunroof","6 Airbags","Wireless Charging"],
    pros:["Affordable compact","360 camera in class","Smooth CVT"],
    cons:["Average build quality","Cramped rear"],
    safetyRating:3, depreciationRate:17, maintenanceCostPerYear:24000,
    insuranceCostPerYear:42000, totalCostOfOwnership5yr:2200000,
    analyticsScore:72, marketTrend:"stable", demandIndex:68,
    tag:"Budget Compact",
    image:imgStudio("nissan","magnite",2024), imageVerified:true
  },
  {
    id:30, make:"Renault", model:"Kiger", year:2024, variant:"RXZ Turbo CVT",
    price:1150000, category:"Compact SUV", fuel:"Petrol", transmission:"CVT",
    mileage:18.2, engine:"1.0L HRA0 Turbo", power:"100 hp", torque:"160 Nm",
    seats:5, color:"Moonlight Silver", rating:4.0, reviews:170,
    features:["8\" MediaNAV","360 Camera","Wireless Charging","6 Airbags","Sunroof"],
    pros:["Affordable","360 camera","Turbo performance"],
    cons:["Unreliable electronics","Limited service"],
    safetyRating:3, depreciationRate:18, maintenanceCostPerYear:22000,
    insuranceCostPerYear:40000, totalCostOfOwnership5yr:2100000,
    analyticsScore:68, marketTrend:"stable", demandIndex:60,
    tag:"Value Turbo",
    image:imgStudio("renault","kiger",2024), imageVerified:true
  },
  {
    id:31, make:"Volkswagen", model:"Taigun", year:2024, variant:"Topline 1.5 TSI DSG",
    price:2000000, category:"Compact SUV", fuel:"Petrol", transmission:"DSG",
    mileage:16.0, engine:"1.5L TSI EVO ACT", power:"150 hp", torque:"250 Nm",
    seats:5, color:"Rising Blue", rating:4.5, reviews:190,
    features:["10\" Touchscreen","Sunroof","6 Airbags","Travel Assist ADAS","Wireless Charging"],
    pros:["European build","GT performance","DSG smooth"],
    cons:["Expensive service","Limited dealer network"],
    safetyRating:5, depreciationRate:15, maintenanceCostPerYear:48000,
    insuranceCostPerYear:72000, totalCostOfOwnership5yr:3200000,
    analyticsScore:86, marketTrend:"stable", demandIndex:70,
    tag:"Euro Compact",
    image:imgStudio("volkswagen","taigun",2024), imageVerified:true
  },
  {
    id:32, make:"Skoda", model:"Kushaq", year:2024, variant:"Monte Carlo 1.5 TSI DSG",
    price:2100000, category:"Compact SUV", fuel:"Petrol", transmission:"DSG",
    mileage:16.0, engine:"1.5L TSI EVO ACT", power:"150 hp", torque:"250 Nm",
    seats:5, color:"Corrida Red", rating:4.5, reviews:175,
    features:["10\" Virtual Cockpit","Sunroof","Canton Audio","6 Airbags","ADAS"],
    pros:["Sport-tuned suspension","Premium quality","Great performance"],
    cons:["Expensive","Limited service centres"],
    safetyRating:5, depreciationRate:15, maintenanceCostPerYear:48000,
    insuranceCostPerYear:74000, totalCostOfOwnership5yr:3300000,
    analyticsScore:86, marketTrend:"stable", demandIndex:65,
    tag:"Sport Czech",
    image:imgStudio("skoda","kushaq",2024), imageVerified:true
  },
  {
    id:33, make:"Citroen", model:"C3 Aircross", year:2024, variant:"Max Turbo AT 7S",
    price:1350000, category:"Compact SUV", fuel:"Petrol", transmission:"AT",
    mileage:17.4, engine:"1.2L PureTech Turbo", power:"110 hp", torque:"190 Nm",
    seats:7, color:"Perla Nera Black", rating:4.1, reviews:88,
    features:["10\" Touchscreen","7-seat option","Wireless Charging","LED Headlamps","6 Airbags"],
    pros:["7 seater compact","Unique design","Comfortable suspension"],
    cons:["Limited service","Brand awareness low"],
    safetyRating:3, depreciationRate:18, maintenanceCostPerYear:30000,
    insuranceCostPerYear:45000, totalCostOfOwnership5yr:2300000,
    analyticsScore:70, marketTrend:"stable", demandIndex:50,
    tag:"7-Seat Compact",
    image:imgStudio("citroen","c3-aircross",2024), imageVerified:true
  },
  {
    id:83, make:"Maruti", model:"Jimny", year:2024, variant:"Zeta AT 4WD",
    price:1505000, category:"Compact SUV", fuel:"Petrol", transmission:"AT",
    mileage:16.39, engine:"1.5L K15B", power:"105 hp", torque:"134 Nm",
    seats:5, color:"Kinetic Yellow", rating:4.5, reviews:280,
    features:["9\" SmartPlay Pro","ALLGRIP 4WD","Rear Camera","6 Airbags","Hill Hold Assist","Snorkel Ready"],
    pros:["Genuine 4WD off-roader","Iconic design","Best-in-class off-road"],
    cons:["Underpowered on highway","No diesel option","Stiff ride"],
    safetyRating:4, depreciationRate:8, maintenanceCostPerYear:22000,
    insuranceCostPerYear:50000, totalCostOfOwnership5yr:2700000,
    analyticsScore:85, marketTrend:"rising", demandIndex:88,
    tag:"Off-Road Gem",
    image:imgStudio("suzuki","jimny",2024), imageVerified:true
  },
  {
    id:84, make:"Maruti", model:"Fronx", year:2024, variant:"Alpha Turbo AT",
    price:1265000, category:"Compact SUV", fuel:"Petrol", transmission:"AT",
    mileage:21.79, engine:"1.0L Boosterjet Turbo", power:"100 hp", torque:"148 Nm",
    seats:5, color:"Nexa Blue", rating:4.3, reviews:320,
    features:["SmartPlay Pro","HUD","360 Camera","6 Airbags","Sunroof","Wireless Charging"],
    pros:["Turbo efficiency","Coupe SUV styling","NEXA premium"],
    cons:["No diesel","3-cylinder engine NVH"],
    safetyRating:4, depreciationRate:11, maintenanceCostPerYear:20000,
    insuranceCostPerYear:44000, totalCostOfOwnership5yr:2300000,
    analyticsScore:83, marketTrend:"rising", demandIndex:86,
    tag:"Coupe Compact",
    image:imgStudio("suzuki","fronx",2024), imageVerified:true
  },

  /* ── MID-SIZE SUVs ───────────────────────────────────────── */
  {
    id:34, make:"Hyundai", model:"Creta", year:2024, variant:"SX(O) Turbo DCT",
    price:2100000, category:"SUV", fuel:"Petrol", transmission:"DCT",
    mileage:16.8, engine:"1.5L Turbo GDi", power:"160 hp", torque:"253 Nm",
    seats:5, color:"Titan Grey", rating:4.6, reviews:820,
    features:["Panoramic Sunroof","BOSE Audio","360 Camera","Level 2 ADAS","Ventilated Seats","Bluelink"],
    pros:["Feature-loaded","Sporty performance","Premium feel","5-star safety"],
    cons:["Firm ride quality","Expensive top variant"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:38000,
    insuranceCostPerYear:72000, totalCostOfOwnership5yr:3600000,
    analyticsScore:93, marketTrend:"rising", demandIndex:97,
    tag:"Top Rated",
    image:imgStudio("hyundai","creta",2024), imageVerified:true
  },
  {
    id:35, make:"Kia", model:"Seltos", year:2024, variant:"X-Line GTX+ DCT",
    price:2350000, category:"SUV", fuel:"Petrol", transmission:"DCT",
    mileage:16.1, engine:"1.5L T-GDi Turbo", power:"160 hp", torque:"253 Nm",
    seats:5, color:"Interstellar Grey", rating:4.5, reviews:450,
    features:["Dual Panoramic Display","Bose Audio","360 Camera","ADAS Level 2","HUD","Ventilated Seats"],
    pros:["Bold styling","Feature-rich","Strong performance"],
    cons:["Expensive variant","Firm ride"],
    safetyRating:5, depreciationRate:14, maintenanceCostPerYear:42000,
    insuranceCostPerYear:78000, totalCostOfOwnership5yr:3950000,
    analyticsScore:91, marketTrend:"rising", demandIndex:86,
    tag:"Style Leader",
    image:imgStudio("kia","seltos",2024), imageVerified:true
  },
  {
    id:36, make:"Maruti", model:"Grand Vitara", year:2024, variant:"Alpha+ Hybrid AWD",
    price:2200000, category:"SUV", fuel:"Hybrid", transmission:"e-CVT",
    mileage:27.97, engine:"1.5L TNGA Strong Hybrid", power:"116 hp", torque:"141 Nm",
    seats:5, color:"Nexa Blue", rating:4.5, reviews:310,
    features:["9\" SmartPlay Pro","ADAS","Sunroof","AWD","Wireless Charging","HUD"],
    pros:["Best-in-class mileage","Strong hybrid","AWD option"],
    cons:["Hybrid premium costly","Limited boot"],
    safetyRating:5, depreciationRate:11, maintenanceCostPerYear:25000,
    insuranceCostPerYear:72000, totalCostOfOwnership5yr:3400000,
    analyticsScore:90, marketTrend:"rising", demandIndex:85,
    tag:"Hybrid SUV",
    image:imgStudio("suzuki","grand-vitara",2024), imageVerified:true
  },
  {
    id:37, make:"Toyota", model:"Urban Cruiser Hyryder", year:2024, variant:"V Hybrid e-CVT",
    price:2100000, category:"SUV", fuel:"Hybrid", transmission:"e-CVT",
    mileage:27.97, engine:"1.5L TNGA Strong Hybrid", power:"116 hp", torque:"141 Nm",
    seats:5, color:"Cafe White", rating:4.5, reviews:270,
    features:["9\" Touchscreen","ADAS","Sunroof","Hybrid","6 Airbags","Wireless Charging"],
    pros:["Exceptional mileage","Toyota reliability","Hybrid efficiency"],
    cons:["Slight power deficit on highway","Limited differentiator from Vitara"],
    safetyRating:5, depreciationRate:11, maintenanceCostPerYear:25000,
    insuranceCostPerYear:70000, totalCostOfOwnership5yr:3350000,
    analyticsScore:89, marketTrend:"rising", demandIndex:78,
    tag:"Toyota Hybrid",
    image:imgStudio("toyota","urban-cruiser",2024), imageVerified:true
  },
  {
    id:38, make:"Honda", model:"Elevate", year:2024, variant:"ZX CVT",
    price:1920000, category:"SUV", fuel:"Petrol", transmission:"CVT",
    mileage:16.92, engine:"1.5L i-VTEC DOHC", power:"121 hp", torque:"145 Nm",
    seats:5, color:"Platinum White", rating:4.3, reviews:240,
    features:["10.25\" Touchscreen","Honda Connect","Sunroof","6 Airbags","ADAS Lane Watch"],
    pros:["Spacious interior","Smooth CVT","Honda reliability"],
    cons:["Less powerful vs turbo rivals","Average styling"],
    safetyRating:5, depreciationRate:14, maintenanceCostPerYear:32000,
    insuranceCostPerYear:65000, totalCostOfOwnership5yr:3200000,
    analyticsScore:82, marketTrend:"stable", demandIndex:72,
    tag:"Honda Premium",
    image:imgStudio("honda","elevate",2024), imageVerified:true
  },
  {
    id:39, make:"MG", model:"Astor", year:2024, variant:"Savvy Turbo CVT",
    price:1850000, category:"SUV", fuel:"Petrol", transmission:"CVT",
    mileage:15.4, engine:"1.3L Turbo", power:"143 hp", torque:"220 Nm",
    seats:5, color:"Starry Black", rating:4.2, reviews:155,
    features:["10.1\" Touchscreen","AI Personal Assistant","ADAS","360 Camera","Sunroof","Ventilated Seats"],
    pros:["AI assistant","Rich features","Strong turbo"],
    cons:["Service network sparse","Brand perception"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:35000,
    insuranceCostPerYear:65000, totalCostOfOwnership5yr:3200000,
    analyticsScore:80, marketTrend:"stable", demandIndex:62,
    tag:"AI-First SUV",
    image:imgStudio("mg","astor",2024), imageVerified:false,
    pressImageUrl:wikiImg("MG_Astor_front.jpg")
  },
  {
    id:40, make:"Jeep", model:"Compass", year:2024, variant:"Limited Plus 4x4 AT",
    price:3200000, category:"SUV", fuel:"Diesel", transmission:"AT",
    mileage:17.0, engine:"2.0L MultiJet II", power:"170 hp", torque:"350 Nm",
    seats:5, color:"Granite Crystal", rating:4.4, reviews:142,
    features:["10.1\" Touchscreen","4WD","Meridian Audio","Sunroof","9 Airbags","ADAS"],
    pros:["4x4 capable","Premium brand","Best-in-class 4WD"],
    cons:["Expensive","High service cost"],
    safetyRating:5, depreciationRate:17, maintenanceCostPerYear:85000,
    insuranceCostPerYear:108000, totalCostOfOwnership5yr:5200000,
    analyticsScore:83, marketTrend:"stable", demandIndex:60,
    tag:"Off-Road Ready",
    image:imgStudio("jeep","compass",2024), imageVerified:true
  },
  {
    id:85, make:"Hyundai", model:"Tucson", year:2024, variant:"Signature 2WD AT",
    price:2902000, category:"SUV", fuel:"Petrol", transmission:"AT",
    mileage:13.6, engine:"2.0L MPi Nu Petrol", power:"156 hp", torque:"192 Nm",
    seats:5, color:"Amazon Grey", rating:4.5, reviews:130,
    features:["10.25\" Touchscreen","Bose Audio","Panoramic Sunroof","ADAS Level 2","Bluelink","Ventilated Seats"],
    pros:["Bold parametric design","Premium feature list","Smooth ride"],
    cons:["Expensive","Fuel thirsty"],
    safetyRating:5, depreciationRate:15, maintenanceCostPerYear:55000,
    insuranceCostPerYear:100000, totalCostOfOwnership5yr:4600000,
    analyticsScore:84, marketTrend:"stable", demandIndex:62,
    tag:"Bold Premium",
    image:imgStudio("hyundai","tucson",2024), imageVerified:true
  },

  /* ── LARGE SUVs ──────────────────────────────────────────── */
  {
    id:41, make:"Mahindra", model:"Scorpio-N", year:2024, variant:"Z8 L AT 4WD",
    price:2450000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:15.2, engine:"2.2L mHawk185 Diesel", power:"175 hp", torque:"400 Nm",
    seats:7, color:"Deep Forest", rating:4.5, reviews:560,
    features:["8\" Touchscreen","Sony Audio","4WD","ADAS","AdrenoX Connected","9 Airbags"],
    pros:["4WD at great price","Road presence","Best diesel in class"],
    cons:["Firm ride on rough roads","City driving tough"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:45000,
    insuranceCostPerYear:85000, totalCostOfOwnership5yr:3900000,
    analyticsScore:89, marketTrend:"rising", demandIndex:92,
    tag:"Road Warrior",
    image:imgStudio("mahindra","scorpio-n",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_Scorpio-N_front.jpg")
  },
  {
    id:42, make:"Mahindra", model:"XUV700", year:2024, variant:"AX7 L Turbo AT AWD",
    price:2800000, category:"Large SUV", fuel:"Petrol", transmission:"AT",
    mileage:13.3, engine:"2.0L mStallion mTurbo Petrol", power:"200 hp", torque:"380 Nm",
    seats:7, color:"Midnight Black", rating:4.7, reviews:480,
    features:["10.25\" Dual Screens","Bose Audio","ADAS+","AWD","AdrenoX","Sunroof","TPMS"],
    pros:["Best value 7-seater","Powerful AWD","ADAS+ tech"],
    cons:["Long waiting period","ADAS can be erratic"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:50000,
    insuranceCostPerYear:95000, totalCostOfOwnership5yr:4400000,
    analyticsScore:94, marketTrend:"rising", demandIndex:95,
    tag:"India's Best SUV",
    image:imgStudio("mahindra","xuv700",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_XUV700_front.jpg")
  },
  {
    id:43, make:"Mahindra", model:"Thar ROXX", year:2024, variant:"MX5 4WD AT",
    price:2350000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:15.2, engine:"2.2L mHawk185 Diesel", power:"175 hp", torque:"370 Nm",
    seats:5, color:"Thar Red", rating:4.8, reviews:390,
    features:["10.25\" Infotainment","Sony Audio","4WD","ADAS","9 Airbags","Wireless Charging"],
    pros:["4WD off-roader","Icon status","Great for hills"],
    cons:["Firm ride","Not for city daily use"],
    safetyRating:5, depreciationRate:8, maintenanceCostPerYear:40000,
    insuranceCostPerYear:80000, totalCostOfOwnership5yr:3700000,
    analyticsScore:91, marketTrend:"rising", demandIndex:89,
    tag:"Off-Road Icon",
    image:imgStudio("mahindra","thar",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_Thar_ROXX_front.jpg")
  },
  {
    id:44, make:"Tata", model:"Harrier", year:2024, variant:"Accomplished+ AT",
    price:2500000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:16.35, engine:"2.0L Kryotec 200 Diesel", power:"170 hp", torque:"350 Nm",
    seats:5, color:"Oberon Black", rating:4.5, reviews:330,
    features:["12.3\" Touchscreen","JBL Audio","Panoramic Sunroof","ADAS","iRA","9 Airbags"],
    pros:["Stunning design","5-star GNCAP safety","Powerful diesel"],
    cons:["No AWD option","Limited petrol variant"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:42000,
    insuranceCostPerYear:88000, totalCostOfOwnership5yr:4100000,
    analyticsScore:88, marketTrend:"rising", demandIndex:82,
    tag:"Design Leader",
    image:imgStudio("tata","harrier",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Harrier_facelift_2023.jpg")
  },
  {
    id:45, make:"Tata", model:"Safari", year:2024, variant:"Accomplished+ AT 7S",
    price:2800000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:16.13, engine:"2.0L Kryotec 200 Diesel", power:"170 hp", torque:"350 Nm",
    seats:7, color:"Oberon Black", rating:4.5, reviews:290,
    features:["12.3\" Touchscreen","JBL Audio","Panoramic Sunroof","ADAS","9 Airbags","7 seats"],
    pros:["7 seats + 5-star safety","Premium 3-row SUV","iRA connected"],
    cons:["3rd row cramped for adults","Diesel only option"],
    safetyRating:5, depreciationRate:13, maintenanceCostPerYear:44000,
    insuranceCostPerYear:95000, totalCostOfOwnership5yr:4400000,
    analyticsScore:87, marketTrend:"rising", demandIndex:79,
    tag:"7-Seat Safe",
    image:imgStudio("tata","safari",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Safari_2021_facelift.jpg")
  },
  {
    id:46, make:"Hyundai", model:"Alcazar", year:2024, variant:"Signature Turbo DCT 7S",
    price:2500000, category:"Large SUV", fuel:"Petrol", transmission:"DCT",
    mileage:14.5, engine:"1.5L Turbo GDi", power:"160 hp", torque:"253 Nm",
    seats:7, color:"Abyss Black", rating:4.4, reviews:220,
    features:["10.25\" Touchscreen","Bose Audio","Panoramic Sunroof","ADAS","7 seats","Ventilated Seats"],
    pros:["7 seats + turbo","Premium Hyundai","ADAS packed"],
    cons:["3rd row cramped","Expensive for Hyundai"],
    safetyRating:5, depreciationRate:14, maintenanceCostPerYear:42000,
    insuranceCostPerYear:85000, totalCostOfOwnership5yr:4100000,
    analyticsScore:85, marketTrend:"stable", demandIndex:72,
    tag:"7-Seat Turbo",
    image:imgStudio("hyundai","alcazar",2024), imageVerified:true
  },
  {
    id:47, make:"Kia", model:"Carens", year:2024, variant:"Luxury Plus Turbo DCT",
    price:2150000, category:"Large SUV", fuel:"Petrol", transmission:"DCT",
    mileage:15.9, engine:"1.5L T-GDi Turbo", power:"160 hp", torque:"253 Nm",
    seats:7, color:"Aurora Black Pearl", rating:4.4, reviews:265,
    features:["10.25\" Touchscreen","Bose Audio","Sunroof","ADAS","6 Airbags","7 seats"],
    pros:["Practical MPV-SUV","7 seats","Best value 7-seater"],
    cons:["Kia service cost","Not a pure SUV"],
    safetyRating:5, depreciationRate:14, maintenanceCostPerYear:38000,
    insuranceCostPerYear:75000, totalCostOfOwnership5yr:3800000,
    analyticsScore:86, marketTrend:"rising", demandIndex:78,
    tag:"Smart 7-Seater",
    image:imgStudio("kia","carens",2024), imageVerified:true
  },
  {
    id:48, make:"MG", model:"Hector Plus", year:2024, variant:"Sharp Pro Turbo CVT 7S",
    price:2300000, category:"Large SUV", fuel:"Petrol", transmission:"CVT",
    mileage:14.0, engine:"1.5L Turbo Petrol", power:"143 hp", torque:"250 Nm",
    seats:7, color:"Starry Black", rating:4.2, reviews:195,
    features:["14\" Touchscreen","i-SMART AI","ADAS","7 seats","Wireless Charging","Sunroof"],
    pros:["India's largest screen","7 seats","AI commands"],
    cons:["Service sparse","CVT not sporty"],
    safetyRating:4, depreciationRate:16, maintenanceCostPerYear:40000,
    insuranceCostPerYear:78000, totalCostOfOwnership5yr:3800000,
    analyticsScore:79, marketTrend:"stable", demandIndex:65,
    tag:"Giant Screen",
    image:imgStudio("mg","hector",2024), imageVerified:false,
    pressImageUrl:wikiImg("MG_Hector_Plus_facelift.jpg")
  },
  {
    id:52, make:"Mahindra", model:"Bolero Neo", year:2024, variant:"N10",
    price:1150000, category:"Large SUV", fuel:"Diesel", transmission:"Manual",
    mileage:17.27, engine:"1.5L mHawk80 Diesel", power:"100 hp", torque:"260 Nm",
    seats:7, color:"Rocky Beige", rating:4.1, reviews:280,
    features:["7\" Touchscreen","7 Seats","4WD option","Rear Camera","Rear AC"],
    pros:["Rugged build","Low maintenance","Rural terrain ready"],
    cons:["Dated interior","No automatic option"],
    safetyRating:3, depreciationRate:10, maintenanceCostPerYear:28000,
    insuranceCostPerYear:40000, totalCostOfOwnership5yr:2400000,
    analyticsScore:72, marketTrend:"stable", demandIndex:75,
    tag:"Rural Workhorse",
    image:imgStudio("mahindra","bolero-neo",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_Bolero_Neo_front.jpg")
  },
  {
    id:53, make:"Toyota", model:"Fortuner", year:2024, variant:"Legender 4WD AT",
    price:4900000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:14.24, engine:"2.8L GD Series Diesel", power:"204 hp", torque:"500 Nm",
    seats:7, color:"Avant-Garde Bronze", rating:4.8, reviews:380,
    features:["9\" Touchscreen","JBL Audio","4WD","LED Matrix","360 Camera","TSS ADAS"],
    pros:["Status symbol","Best 4WD","Bulletproof reliability"],
    cons:["Very expensive to run","Interior lags premium rivals"],
    safetyRating:5, depreciationRate:9, maintenanceCostPerYear:90000,
    insuranceCostPerYear:165000, totalCostOfOwnership5yr:7300000,
    analyticsScore:89, marketTrend:"stable", demandIndex:82,
    tag:"Status SUV",
    image:imgStudio("toyota","fortuner",2024), imageVerified:true
  },
  {
    id:54, make:"Jeep", model:"Meridian", year:2024, variant:"4x4 Overland AT",
    price:4300000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:14.5, engine:"2.0L MultiJet II Diesel", power:"170 hp", torque:"350 Nm",
    seats:7, color:"Brilliant Black Crystal", rating:4.4, reviews:108,
    features:["10.1\" Touchscreen","Meridian Audio","4x4","Sunroof","9 Airbags","ADAS"],
    pros:["4x4 7-seater","Premium brand","Off-road + luxury"],
    cons:["High price","Limited service network"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:110000,
    insuranceCostPerYear:148000, totalCostOfOwnership5yr:7100000,
    analyticsScore:82, marketTrend:"stable", demandIndex:52,
    tag:"4x4 Premium 7S",
    image:imgStudio("jeep","meridian",2024), imageVerified:true
  },
  {
    id:88, make:"MG", model:"Gloster", year:2024, variant:"Savvy 4WD AT",
    price:4450000, category:"Large SUV", fuel:"Diesel", transmission:"AT",
    mileage:13.0, engine:"2.0L Twin Turbo Diesel", power:"218 hp", torque:"480 Nm",
    seats:7, color:"Starry Black", rating:4.3, reviews:88,
    features:["12.3\" Touchscreen","ADAS","4WD","Sunroof","7 seats","Wireless Charging","Ambient Lighting"],
    pros:["218hp twin turbo","Feature-rich","Premium feel"],
    cons:["Limited MG service","Brand perception vs Toyota/Jeep"],
    safetyRating:4, depreciationRate:18, maintenanceCostPerYear:95000,
    insuranceCostPerYear:155000, totalCostOfOwnership5yr:7500000,
    analyticsScore:78, marketTrend:"stable", demandIndex:48,
    tag:"Twin Turbo SUV",
    image:imgStudio("mg","gloster",2024), imageVerified:false,
    pressImageUrl:wikiImg("MG_Gloster_front.jpg")
  },
  {
    id:89, make:"Skoda", model:"Kodiaq", year:2024, variant:"Sportline 2.0 TSI DSG",
    price:4689000, category:"Large SUV", fuel:"Petrol", transmission:"DSG",
    mileage:10.9, engine:"2.0L TSI 4-cylinder Turbo", power:"190 hp", torque:"320 Nm",
    seats:7, color:"Graphite Grey", rating:4.6, reviews:65,
    features:["Virtual Cockpit Plus","Canton Audio","Panoramic Sunroof","7 seats","DSG","ADAS"],
    pros:["European 7-seat SUV","DSG smooth","Premium feel"],
    cons:["Very expensive","Fuel thirsty","Limited dealers"],
    safetyRating:5, depreciationRate:18, maintenanceCostPerYear:150000,
    insuranceCostPerYear:172000, totalCostOfOwnership5yr:8500000,
    analyticsScore:82, marketTrend:"stable", demandIndex:38,
    tag:"Euro 7-Seat",
    image:imgStudio("skoda","kodiaq",2024), imageVerified:true
  },

  /* ── MPVs ───────────────────────────────────────────────── */
  {
    id:49, make:"Toyota", model:"Innova HyCross", year:2024, variant:"ZX Hybrid CVT",
    price:3600000, category:"MPV", fuel:"Hybrid", transmission:"e-CVT",
    mileage:21.1, engine:"2.0L TNGA Series Hybrid", power:"186 hp combined", torque:"188 Nm",
    seats:8, color:"Super White", rating:4.8, reviews:420,
    features:["10.1\" Touchscreen","JBL Audio","Sunroof","Hybrid","8 Seats","ADAS","Wireless Charging"],
    pros:["Iconic reliability","Hybrid efficiency","Premium MPV feel"],
    cons:["Expensive","No diesel option"],
    safetyRating:5, depreciationRate:9, maintenanceCostPerYear:55000,
    insuranceCostPerYear:120000, totalCostOfOwnership5yr:5600000,
    analyticsScore:93, marketTrend:"rising", demandIndex:88,
    tag:"Premium MPV",
    image:imgStudio("toyota","innova-hycross",2024), imageVerified:true
  },
  {
    id:50, make:"Toyota", model:"Innova Crysta", year:2024, variant:"GX AT",
    price:2100000, category:"MPV", fuel:"Diesel", transmission:"AT",
    mileage:14.26, engine:"2.4L GD Series 4-cyl Diesel", power:"150 hp", torque:"343 Nm",
    seats:8, color:"Super White", rating:4.7, reviews:680,
    features:["9\" Touchscreen","Rear AC Vents","8 Seats","Toyota Safety Sense","Rear Privacy Glass"],
    pros:["Most reliable MPV ever","Bulletproof diesel","Huge resale value"],
    cons:["Dated interior vs HyCross","No sunroof in GX"],
    safetyRating:4, depreciationRate:8, maintenanceCostPerYear:45000,
    insuranceCostPerYear:75000, totalCostOfOwnership5yr:4200000,
    analyticsScore:91, marketTrend:"stable", demandIndex:90,
    tag:"Evergreen MPV",
    image:imgStudio("toyota","innova",2024), imageVerified:true
  },
  {
    id:51, make:"Maruti", model:"Ertiga", year:2024, variant:"ZXi+ AT",
    price:1400000, category:"MPV", fuel:"Petrol", transmission:"AT",
    mileage:19.34, engine:"1.5L K15C mild-hybrid", power:"103 hp", torque:"137 Nm",
    seats:7, color:"Auburn Red", rating:4.3, reviews:450,
    features:["SmartPlay Pro","Rear AC","6 Airbags","7 Seats","Wireless Charging"],
    pros:["Most affordable 7-seater","Great mileage","Low TCO"],
    cons:["Underpowered with 7 onboard","Basic premium features"],
    safetyRating:4, depreciationRate:11, maintenanceCostPerYear:22000,
    insuranceCostPerYear:50000, totalCostOfOwnership5yr:2700000,
    analyticsScore:82, marketTrend:"stable", demandIndex:87,
    tag:"Budget MPV",
    image:imgStudio("suzuki","ertiga",2024), imageVerified:true
  },
  {
    id:86, make:"Toyota", model:"Rumion", year:2024, variant:"Z CVT",
    price:1397000, category:"MPV", fuel:"Petrol", transmission:"CVT",
    mileage:19.34, engine:"1.5L K15C mild-hybrid", power:"103 hp", torque:"137 Nm",
    seats:7, color:"Cafe White", rating:4.3, reviews:145,
    features:["SmartPlay Pro","Rear AC","6 Airbags","7 Seats","Toyota Safety Sense","Wireless Charging"],
    pros:["Toyota reliability stamp on Ertiga","Mild hybrid efficiency","Wide TKM network"],
    cons:["Same as Ertiga under the skin","Higher price than Ertiga"],
    safetyRating:4, depreciationRate:10, maintenanceCostPerYear:22000,
    insuranceCostPerYear:48000, totalCostOfOwnership5yr:2650000,
    analyticsScore:80, marketTrend:"stable", demandIndex:70,
    tag:"Toyota MPV",
    image:imgStudio("toyota","rumion",2024), imageVerified:true
  },
  {
    id:87, make:"Renault", model:"Triber", year:2024, variant:"RXZ MT Turbo",
    price:897000, category:"MPV", fuel:"Petrol", transmission:"Manual",
    mileage:18.64, engine:"1.0L HRA0 Turbo", power:"100 hp", torque:"160 Nm",
    seats:7, color:"Moonlight Silver", rating:4.1, reviews:195,
    features:["8\" MediaNAV","7 Seats","Rear AC","Wireless Charging","6 Airbags"],
    pros:["Cheapest 7-seater","Turbo option","Modular rear seat"],
    cons:["Basic interior","Limited safety features","Renault service sparse"],
    safetyRating:3, depreciationRate:17, maintenanceCostPerYear:20000,
    insuranceCostPerYear:32000, totalCostOfOwnership5yr:2100000,
    analyticsScore:70, marketTrend:"stable", demandIndex:72,
    tag:"Budget 7-Seater",
    image:imgStudio("renault","triber",2024), imageVerified:true
  },
  {
    id:91, make:"Mahindra", model:"Marazzo", year:2024, variant:"M8 AT",
    price:2015000, category:"MPV", fuel:"Diesel", transmission:"AT",
    mileage:17.0, engine:"1.5L mHawk100 Diesel", power:"123 hp", torque:"300 Nm",
    seats:8, color:"Aquamarine Blue", rating:4.2, reviews:120,
    features:["8\" Touchscreen","8 Seats","Rear AC","6 Airbags","Shark-fin Antenna","Hill Descent Control"],
    pros:["Shark-inspired design","8 seats diesel","Comfortable ride"],
    cons:["Dated infotainment","Competing with Crysta"],
    safetyRating:4, depreciationRate:14, maintenanceCostPerYear:38000,
    insuranceCostPerYear:68000, totalCostOfOwnership5yr:3800000,
    analyticsScore:74, marketTrend:"stable", demandIndex:55,
    tag:"Diesel MPV",
    image:imgStudio("mahindra","marazzo",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_Marazzo_front.jpg")
  },

  /* ── ELECTRIC VEHICLES ───────────────────────────────────── */
  {
    id:55, make:"Mahindra", model:"XUV400 EV", year:2024, variant:"EC Pro LR",
    price:1950000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"39.4 kWh Battery", power:"150 hp", torque:"310 Nm",
    seats:5, color:"Everest White", rating:4.3, reviews:210,
    features:["10.25\" Touchscreen","ADAS","Sunroof","Fast Charge 50kW DC","iRA Connected","456km Range"],
    pros:["5-star GNCAP safety","Low running cost","Govt incentives"],
    cons:["Range anxiety in highways","DC charger needed for fast top-up"],
    safetyRating:5, depreciationRate:17, maintenanceCostPerYear:14000,
    insuranceCostPerYear:65000, totalCostOfOwnership5yr:3250000,
    analyticsScore:84, marketTrend:"rising", demandIndex:74,
    tag:"Safe EV",
    image:imgStudio("mahindra","xuv400-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_XUV400_EV_front.jpg")
  },
  {
    id:56, make:"Tata", model:"Nexon EV", year:2024, variant:"Max LR Dark",
    price:2050000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"40.5 kWh Battery", power:"143 hp", torque:"250 Nm",
    seats:5, color:"Daytona Grey", rating:4.4, reviews:380,
    features:["Fast Charging 50kW DC","Connected Car Tech","Air Purifier","Wireless Charger","Sunroof","465km ARAI Range"],
    pros:["Zero emissions","Low running cost","Government incentives"],
    cons:["Charging infrastructure","Range anxiety on long trips"],
    safetyRating:5, depreciationRate:18, maintenanceCostPerYear:15000,
    insuranceCostPerYear:68000, totalCostOfOwnership5yr:2950000,
    analyticsScore:86, marketTrend:"rising", demandIndex:78,
    tag:"Eco Choice",
    image:imgStudio("tata","nexon-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Nexon_EV_Max_2023.jpg")
  },
  {
    id:57, make:"Tata", model:"Tiago EV", year:2024, variant:"XZ+ LR",
    price:1200000, category:"Electric Hatchback", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"24 kWh LFP Battery", power:"75 hp", torque:"114 Nm",
    seats:5, color:"Pristine White", rating:4.2, reviews:290,
    features:["7\" Touchscreen","Rear Camera","iRA Connected","Fast Charge 15kW AC","315km ARAI Range"],
    pros:["Most affordable EV","5-star GNCAP safety","Low running cost"],
    cons:["Limited range 315km","Small cabin","Slow AC charging"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:10000,
    insuranceCostPerYear:40000, totalCostOfOwnership5yr:2100000,
    analyticsScore:80, marketTrend:"rising", demandIndex:82,
    tag:"Affordable EV",
    image:imgStudio("tata","tiago-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Tiago_EV_front.jpg")
  },
  {
    id:58, make:"Tata", model:"Punch EV", year:2024, variant:"Empowered+ LR",
    price:1650000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"35 kWh LFP Battery", power:"122 hp", torque:"190 Nm",
    seats:5, color:"Fearless Purple", rating:4.5, reviews:255,
    features:["10.25\" Touchscreen","ADAS","Sunroof","iRA Connected","421km ARAI Range","Fast Charge 50kW DC"],
    pros:["5-star GNCAP safety EV","421km ARAI range","Practical size"],
    cons:["Long AC charging time","Limited fast chargers"],
    safetyRating:5, depreciationRate:18, maintenanceCostPerYear:12000,
    insuranceCostPerYear:55000, totalCostOfOwnership5yr:2700000,
    analyticsScore:87, marketTrend:"rising", demandIndex:84,
    tag:"EV Star",
    image:imgStudio("tata","punch-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Punch_EV_front.jpg")
  },
  {
    id:59, make:"Tata", model:"Curvv EV", year:2024, variant:"Accomplished+ LR",
    price:2200000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"55 kWh NMC Battery", power:"167 hp", torque:"215 Nm",
    seats:5, color:"Neon Gold", rating:4.6, reviews:185,
    features:["12.3\" Touchscreen","ADAS Level 2","Sunroof","JBL Audio","iRA","502km ARAI Range","Fast Charge 70kW DC"],
    pros:["Coupe SUV design","502km ARAI range","Feature-rich"],
    cons:["Higher price point","Charging wait on road trips"],
    safetyRating:5, depreciationRate:17, maintenanceCostPerYear:13000,
    insuranceCostPerYear:72000, totalCostOfOwnership5yr:3400000,
    analyticsScore:89, marketTrend:"rising", demandIndex:80,
    tag:"EV Coupe",
    image:imgStudio("tata","curvv-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("Tata_Curvv_EV_front.jpg")
  },
  {
    id:60, make:"MG", model:"ZS EV", year:2024, variant:"Exclusive Pro",
    price:2499000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"50.3 kWh NMC Battery", power:"176 hp", torque:"280 Nm",
    seats:5, color:"Candy White", rating:4.3, reviews:175,
    features:["i-SMART Connectivity","PM 2.5 Filter","Panoramic Roof","360 Camera","Fast Charging 76kW DC","461km Range"],
    pros:["Longer range 461km","Spacious cabin","Good tech package"],
    cons:["Service network limited","Brand perception vs Tata"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:18000,
    insuranceCostPerYear:82000, totalCostOfOwnership5yr:3950000,
    analyticsScore:80, marketTrend:"rising", demandIndex:70,
    tag:"EV Premium",
    image:imgStudio("mg","zs-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("MG_ZS_EV_2024_front.jpg")
  },
  {
    id:61, make:"MG", model:"Windsor EV", year:2024, variant:"Essence",
    price:1700000, category:"Electric Hatchback", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"38 kWh NMC Battery", power:"136 hp", torque:"200 Nm",
    seats:5, color:"Pearl White", rating:4.4, reviews:155,
    features:["15.6\" Rotating Touchscreen","i-SMART AI","380km ARAI Range","Wireless Charging","Panoramic Roof"],
    pros:["Rotating giant screen","Comfortable lounge interior","Affordable EV"],
    cons:["Battery-as-a-Service model complexity","Service network limited"],
    safetyRating:4, depreciationRate:19, maintenanceCostPerYear:14000,
    insuranceCostPerYear:58000, totalCostOfOwnership5yr:2800000,
    analyticsScore:82, marketTrend:"rising", demandIndex:77,
    tag:"EV Lounge",
    image:imgStudio("mg","windsor-ev",2024), imageVerified:false,
    pressImageUrl:wikiImg("MG_Windsor_EV_front.jpg")
  },
  {
    id:62, make:"Mahindra", model:"BE 6", year:2024, variant:"Pack Three",
    price:2700000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"79 kWh NMC Battery", power:"231 hp", torque:"380 Nm",
    seats:5, color:"Nebula Blue", rating:4.7, reviews:125,
    features:["12.3\" Touchscreen","ADAS+","Sunroof","682km ARAI Range","175kW Fast DC Charge","Wireless Charging"],
    pros:["682km ARAI range","Most powerful Indian brand EV","Next-gen INGLO platform"],
    cons:["Long delivery wait","Expensive for the segment"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:15000,
    insuranceCostPerYear:90000, totalCostOfOwnership5yr:4100000,
    analyticsScore:92, marketTrend:"rising", demandIndex:88,
    tag:"EV Flagship",
    image:imgStudio("mahindra","be-6e",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_BE_6e_front.jpg")
  },
  {
    id:63, make:"Mahindra", model:"XEV 9e", year:2024, variant:"Pack Three",
    price:3500000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"79 kWh NMC Battery", power:"282 hp", torque:"380 Nm",
    seats:5, color:"Desert Mist", rating:4.7, reviews:98,
    features:["3-Screen Cockpit","ADAS+","656km ARAI Range","AWD option","Dolby Atmos Sound","175kW Fast DC"],
    pros:["Performance EV","3-screen cockpit","656km ARAI range"],
    cons:["Very expensive","Charging infra limited in India"],
    safetyRating:5, depreciationRate:16, maintenanceCostPerYear:15000,
    insuranceCostPerYear:115000, totalCostOfOwnership5yr:5200000,
    analyticsScore:91, marketTrend:"rising", demandIndex:75,
    tag:"EV Superstar",
    image:imgStudio("mahindra","xev-9e",2024), imageVerified:false,
    pressImageUrl:wikiImg("Mahindra_XEV_9e_front.jpg")
  },
  {
    id:64, make:"BYD", model:"Atto 3", year:2024, variant:"Standard",
    price:3399000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"60.5 kWh Blade LFP Battery", power:"204 hp", torque:"310 Nm",
    seats:5, color:"Surf Blue", rating:4.3, reviews:120,
    features:["12.8\" Rotating Screen","ADAS","Blade Battery","484km ARAI Range","Wireless Charging"],
    pros:["Blade LFP battery safety","Rotating screen","484km ARAI range"],
    cons:["Chinese brand perception","Limited service network"],
    safetyRating:5, depreciationRate:19, maintenanceCostPerYear:16000,
    insuranceCostPerYear:110000, totalCostOfOwnership5yr:5100000,
    analyticsScore:80, marketTrend:"rising", demandIndex:62,
    tag:"Chinese EV",
    image:imgStudio("byd","atto-3",2024), imageVerified:true
  },
  {
    id:65, make:"BYD", model:"Seal", year:2024, variant:"Excellence AWD",
    price:4100000, category:"Electric Sedan", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"82.56 kWh Blade LFP Battery", power:"313 hp", torque:"670 Nm AWD",
    seats:5, color:"Mineral Grey", rating:4.4, reviews:88,
    features:["15.6\" Rotating Screen","DiLink 4.0","AWD","570km ARAI Range","ADAS+","Vehicle-to-Load"],
    pros:["Performance EV sedan","AWD 313hp","Great tech package"],
    cons:["Chinese brand","Service rare in India"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:18000,
    insuranceCostPerYear:138000, totalCostOfOwnership5yr:6100000,
    analyticsScore:80, marketTrend:"rising", demandIndex:52,
    tag:"EV Performance Sedan",
    image:imgStudio("byd","seal",2024), imageVerified:true
  },
  {
    id:66, make:"Hyundai", model:"Ioniq 5", year:2024, variant:"RWD Standard Range",
    price:4599000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"58 kWh NMC Battery", power:"170 hp", torque:"350 Nm",
    seats:5, color:"Lucid Blue", rating:4.6, reviews:102,
    features:["12\" Dual Screens","V2L Vehicle-to-Load","ADAS","800V Ultra Fast Charge","Sunroof","631km WLTP Range"],
    pros:["800V ultra fast charging","V2L feature unique","Iconic angular design"],
    cons:["Expensive price","India WLTP vs real range gap"],
    safetyRating:5, depreciationRate:18, maintenanceCostPerYear:20000,
    insuranceCostPerYear:150000, totalCostOfOwnership5yr:6800000,
    analyticsScore:85, marketTrend:"rising", demandIndex:62,
    tag:"Global EV",
    image:imgStudio("hyundai","ioniq-5",2024), imageVerified:true
  },
  {
    id:67, make:"Kia", model:"EV6", year:2024, variant:"GT Line AWD",
    price:6095000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"77.4 kWh NMC Battery", power:"325 hp", torque:"605 Nm AWD",
    seats:5, color:"Moonscape", rating:4.7, reviews:78,
    features:["12\" Dual Screens","ADAS+","800V Fast Charge","AWD","708km WLTP Range","V2L"],
    pros:["Best range in India 708km WLTP","AWD performance EV","Stunning design"],
    cons:["Very expensive","Charging infra limited"],
    safetyRating:5, depreciationRate:18, maintenanceCostPerYear:22000,
    insuranceCostPerYear:200000, totalCostOfOwnership5yr:9200000,
    analyticsScore:88, marketTrend:"rising", demandIndex:52,
    tag:"Range King EV",
    image:imgStudio("kia","ev6",2024), imageVerified:true
  },
  {
    id:79, make:"Volvo", model:"XC40", year:2024, variant:"Recharge Twin Pure Electric",
    price:5550000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"78 kWh NMC Battery", power:"408 hp", torque:"660 Nm AWD",
    seats:5, color:"Denim Blue", rating:4.7, reviews:65,
    features:["Google Built-in Infotainment","Harman Kardon","ADAS Pilot Assist","AWD","418km WLTP Range"],
    pros:["Safety heritage","Google native OS","AWD EV"],
    cons:["Average real-world range","Limited dealers India"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:35000,
    insuranceCostPerYear:190000, totalCostOfOwnership5yr:9000000,
    analyticsScore:84, marketTrend:"rising", demandIndex:48,
    tag:"Swedish EV",
    image:imgStudio("volvo","xc40-recharge",2024), imageVerified:true
  },
  {
    id:80, make:"Mercedes-Benz", model:"EQS SUV", year:2024, variant:"580 4MATIC",
    price:21000000, category:"Electric SUV", fuel:"Electric", transmission:"Automatic",
    mileage:0, engine:"108.4 kWh NMC Battery", power:"544 hp", torque:"858 Nm",
    seats:7, color:"Obsidian Black", rating:4.9, reviews:22,
    features:["Hyperscreen 55\"","Burmester 4D","ADAS Level 3","4MATIC AWD","809km WLTP Range","Air Suspension"],
    pros:["809km WLTP range","Hyperscreen marvel","Ultra luxury EV"],
    cons:["Astronomical price","Charging infra India limited"],
    safetyRating:5, depreciationRate:22, maintenanceCostPerYear:50000,
    insuranceCostPerYear:720000, totalCostOfOwnership5yr:30000000,
    analyticsScore:90, marketTrend:"rising", demandIndex:18,
    tag:"EV Ultra Luxury",
    image:imgStudio("mercedes-benz","eqs-suv",2024), imageVerified:true
  },

  /* ── LUXURY SEGMENT ──────────────────────────────────────── */
  {
    id:68, make:"BMW", model:"3 Series", year:2024, variant:"320d M Sport",
    price:5750000, category:"Luxury Sedan", fuel:"Diesel", transmission:"Automatic",
    mileage:19.4, engine:"2.0L B47 TwinPower Turbo", power:"190 hp", torque:"400 Nm",
    seats:5, color:"Mineral White", rating:4.8, reviews:95,
    features:["Live Cockpit Pro 12.3\"","Harman Kardon","Driving Assistant Pro","Ambient Lighting","M Sport Package"],
    pros:["Exceptional driving dynamics","Premium brand","Tech-loaded interior"],
    cons:["High maintenance cost","Expensive servicing"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:180000,
    insuranceCostPerYear:210000, totalCostOfOwnership5yr:7700000,
    analyticsScore:85, marketTrend:"stable", demandIndex:65,
    tag:"Premium Pick",
    image:imgStudio("bmw","3-series",2024), imageVerified:true
  },
  {
    id:69, make:"BMW", model:"5 Series", year:2024, variant:"520d M Sport",
    price:7600000, category:"Luxury Sedan", fuel:"Diesel", transmission:"Automatic",
    mileage:16.1, engine:"2.0L B47 TwinPower Turbo", power:"190 hp", torque:"400 Nm",
    seats:5, color:"Carbon Black", rating:4.8, reviews:72,
    features:["Curved Display 14.9\"","Harman Kardon","ADAS Level 2","Ambient Light","Panoramic Roof","Rear Screen"],
    pros:["Executive presence","Best-in-class tech","Smooth ride"],
    cons:["Very high TCO","Expensive maintenance"],
    safetyRating:5, depreciationRate:21, maintenanceCostPerYear:240000,
    insuranceCostPerYear:280000, totalCostOfOwnership5yr:10000000,
    analyticsScore:87, marketTrend:"stable", demandIndex:48,
    tag:"Executive BMW",
    image:imgStudio("bmw","5-series",2024), imageVerified:true
  },
  {
    id:70, make:"Mercedes-Benz", model:"C-Class", year:2024, variant:"C 220d AMG Line",
    price:7050000, category:"Luxury Sedan", fuel:"Diesel", transmission:"Automatic",
    mileage:18.0, engine:"2.0L OM 654M Diesel", power:"200 hp", torque:"440 Nm",
    seats:5, color:"Spectral Blue", rating:4.9, reviews:88,
    features:["11.9\" MBUX","Burmester 3D Audio","Sunroof","ADAS+","Ambient Light 64-color","Heated Seats"],
    pros:["Best interior in class","MBUX AI assistant","Stunning design"],
    cons:["Extremely high service cost","High depreciation"],
    safetyRating:5, depreciationRate:22, maintenanceCostPerYear:260000,
    insuranceCostPerYear:260000, totalCostOfOwnership5yr:10500000,
    analyticsScore:89, marketTrend:"stable", demandIndex:55,
    tag:"Star Class",
    image:imgStudio("mercedes-benz","c-class",2024), imageVerified:true
  },
  {
    id:71, make:"Mercedes-Benz", model:"E-Class", year:2024, variant:"E 220d AMG Line",
    price:9750000, category:"Luxury Sedan", fuel:"Diesel", transmission:"Automatic",
    mileage:16.0, engine:"2.0L OM 654M Diesel", power:"200 hp", torque:"440 Nm",
    seats:5, color:"High-Tech Silver", rating:4.9, reviews:62,
    features:["MBUX Hyperscreen 55\"","Burmester 4D","Rear-Wheel Steering","ADAS Level 3","64-color Ambient"],
    pros:["Hyperscreen excellence","Rear-wheel steering","Best-in-class luxury"],
    cons:["Astronomical running costs","High depreciation"],
    safetyRating:5, depreciationRate:23, maintenanceCostPerYear:320000,
    insuranceCostPerYear:340000, totalCostOfOwnership5yr:14000000,
    analyticsScore:90, marketTrend:"stable", demandIndex:40,
    tag:"Uber Luxury",
    image:imgStudio("mercedes-benz","e-class",2024), imageVerified:true
  },
  {
    id:72, make:"Audi", model:"A4", year:2024, variant:"40 TFSI Premium Plus",
    price:5500000, category:"Luxury Sedan", fuel:"Petrol", transmission:"S-tronic",
    mileage:13.9, engine:"2.0L EA888 TFSI", power:"190 hp", torque:"320 Nm",
    seats:5, color:"Floret Silver", rating:4.7, reviews:82,
    features:["Virtual Cockpit Plus 12.3\"","Bang & Olufsen","ADAS","Sunroof","Matrix LED"],
    pros:["Quattro AWD option","Virtual cockpit","Sporty handling"],
    cons:["High maintenance","Petrol thirsty"],
    safetyRating:5, depreciationRate:21, maintenanceCostPerYear:220000,
    insuranceCostPerYear:200000, totalCostOfOwnership5yr:9000000,
    analyticsScore:84, marketTrend:"stable", demandIndex:52,
    tag:"Vorsprung",
    image:imgStudio("audi","a4",2024), imageVerified:true
  },
  {
    id:73, make:"BMW", model:"X1", year:2024, variant:"sDrive20i M Sport",
    price:5200000, category:"Luxury SUV", fuel:"Petrol", transmission:"Automatic",
    mileage:13.4, engine:"2.0L B48 TwinPower Turbo", power:"204 hp", torque:"300 Nm",
    seats:5, color:"Phytonic Blue", rating:4.7, reviews:108,
    features:["Curved Display 10.7\"","Harman Kardon","Panoramic Roof","ADAS","M Sport"],
    pros:["Best compact luxury SUV","Sporty","Tech-packed"],
    cons:["High maintenance","Petrol fuel cost"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:200000,
    insuranceCostPerYear:190000, totalCostOfOwnership5yr:8700000,
    analyticsScore:86, marketTrend:"stable", demandIndex:62,
    tag:"Compact Luxury SUV",
    image:imgStudio("bmw","x1",2024), imageVerified:true
  },
  {
    id:74, make:"Mercedes-Benz", model:"GLA", year:2024, variant:"GLA 220d 4MATIC",
    price:6350000, category:"Luxury SUV", fuel:"Diesel", transmission:"Automatic",
    mileage:15.0, engine:"2.0L OM654M Diesel", power:"200 hp", torque:"400 Nm",
    seats:5, color:"Night Black", rating:4.7, reviews:92,
    features:["MBUX 10.25\"","Burmester Audio","Panoramic Roof","4MATIC AWD","ADAS+"],
    pros:["4MATIC all-weather","MBUX interface","Premium safety"],
    cons:["Rear space tight","High maintenance"],
    safetyRating:5, depreciationRate:21, maintenanceCostPerYear:240000,
    insuranceCostPerYear:230000, totalCostOfOwnership5yr:10200000,
    analyticsScore:85, marketTrend:"stable", demandIndex:55,
    tag:"Star SUV",
    image:imgStudio("mercedes-benz","gla",2024), imageVerified:true
  },
  {
    id:75, make:"Audi", model:"Q3", year:2024, variant:"40 TFSI S-Line",
    price:5800000, category:"Luxury SUV", fuel:"Petrol", transmission:"S-tronic",
    mileage:11.9, engine:"2.0L EA888 TFSI Turbo", power:"190 hp", torque:"320 Nm",
    seats:5, color:"Arrow Grey", rating:4.6, reviews:78,
    features:["Virtual Cockpit 10.1\"","Bang & Olufsen","Panoramic Roof","quattro AWD","Matrix LED"],
    pros:["quattro AWD","Premium brand","Great on highways"],
    cons:["Thirsty engine","Expensive service"],
    safetyRating:5, depreciationRate:21, maintenanceCostPerYear:230000,
    insuranceCostPerYear:218000, totalCostOfOwnership5yr:9600000,
    analyticsScore:83, marketTrend:"stable", demandIndex:50,
    tag:"Quattro SUV",
    image:imgStudio("audi","q3",2024), imageVerified:true
  },
  {
    id:76, make:"BMW", model:"X5", year:2024, variant:"xDrive40i M Sport",
    price:11500000, category:"Luxury SUV", fuel:"Petrol", transmission:"Automatic",
    mileage:10.4, engine:"3.0L B58 TwinPower Turbo Inline-6", power:"340 hp", torque:"450 Nm",
    seats:5, color:"Sophisto Grey", rating:4.9, reviews:58,
    features:["Panoramic Sky Lounge","Harman Kardon","ADAS Pro","xDrive AWD","Ambient Light"],
    pros:["Immense performance","Luxury inside","All-terrain xDrive"],
    cons:["Very expensive","Fuel heavy"],
    safetyRating:5, depreciationRate:22, maintenanceCostPerYear:380000,
    insuranceCostPerYear:420000, totalCostOfOwnership5yr:16000000,
    analyticsScore:88, marketTrend:"stable", demandIndex:40,
    tag:"Luxury Powerhouse",
    image:imgStudio("bmw","x5",2024), imageVerified:true
  },
  {
    id:77, make:"Range Rover", model:"Sport", year:2024, variant:"HSE Dynamic Diesel",
    price:16500000, category:"Luxury SUV", fuel:"Diesel", transmission:"Automatic",
    mileage:9.8, engine:"3.0L TD6 Ingenium Diesel", power:"300 hp", torque:"650 Nm",
    seats:5, color:"Serenity", rating:4.9, reviews:42,
    features:["Pivi Pro 13.1\"","Meridian Signature Audio","Terrain Response 2","AWD","Air Suspension"],
    pros:["Ultimate luxury SUV","Best off-road","Brand prestige"],
    cons:["Astronomical price","High maintenance"],
    safetyRating:5, depreciationRate:22, maintenanceCostPerYear:520000,
    insuranceCostPerYear:580000, totalCostOfOwnership5yr:23000000,
    analyticsScore:87, marketTrend:"stable", demandIndex:30,
    tag:"Ultra Premium",
    image:imgStudio("land-rover","range-rover-sport",2024), imageVerified:true
  },
  {
    id:78, make:"Porsche", model:"Cayenne", year:2024, variant:"S",
    price:18000000, category:"Luxury SUV", fuel:"Petrol", transmission:"PDK",
    mileage:9.0, engine:"2.9L Biturbo V6 EA839", power:"474 hp", torque:"600 Nm",
    seats:5, color:"Chalk", rating:5.0, reviews:28,
    features:["PCM Infotainment 12.3\"","Burmester 3D","PASM Air Suspension","Sport Chrono","4WD"],
    pros:["Sports car performance in SUV","Unmatched handling","Top prestige"],
    cons:["Extremely expensive","Highest running cost in India"],
    safetyRating:5, depreciationRate:20, maintenanceCostPerYear:650000,
    insuranceCostPerYear:720000, totalCostOfOwnership5yr:28000000,
    analyticsScore:91, marketTrend:"stable", demandIndex:22,
    tag:"Supercar SUV",
    image:imgStudio("porsche","cayenne",2024), imageVerified:true
  },

  /* ── SPORTS / PERFORMANCE ────────────────────────────────── */
  {
    id:81, make:"BMW", model:"M3 Competition", year:2024, variant:"xDrive",
    price:13900000, category:"Sports Sedan", fuel:"Petrol", transmission:"M DCT",
    mileage:7.0, engine:"3.0L S58 TwinTurbo Inline-6", power:"510 hp", torque:"650 Nm",
    seats:5, color:"Isle of Man Green", rating:5.0, reviews:18,
    features:["M Display 12.3\"","Harman Kardon","M xDrive AWD","M Carbon Bucket Seats","Adaptive M Suspension"],
    pros:["Best driver's car","Track + daily usable","xDrive traction"],
    cons:["Very expensive","High fuel cost","No luggage space"],
    safetyRating:5, depreciationRate:19, maintenanceCostPerYear:500000,
    insuranceCostPerYear:510000, totalCostOfOwnership5yr:22000000,
    analyticsScore:92, marketTrend:"stable", demandIndex:20,
    tag:"M Power",
    image:imgStudio("bmw","m3",2024), imageVerified:true
  },
  {
    id:82, make:"Porsche", model:"911 Carrera", year:2024, variant:"S PDK",
    price:24500000, category:"Sports Car", fuel:"Petrol", transmission:"PDK",
    mileage:9.0, engine:"3.0L MA1 Twin-Turbo Flat-6", power:"450 hp", torque:"530 Nm",
    seats:2, color:"Guards Red", rating:5.0, reviews:12,
    features:["PCM Infotainment","Sport Chrono Plus","PASM","PDK","8-speaker BOSE","Adaptive Cruise"],
    pros:["Iconic sports car","PDK perfection","Daily drivable supercar"],
    cons:["No practical use","Extremely expensive","Running costs"],
    safetyRating:5, depreciationRate:15, maintenanceCostPerYear:750000,
    insuranceCostPerYear:900000, totalCostOfOwnership5yr:35000000,
    analyticsScore:94, marketTrend:"stable", demandIndex:12,
    tag:"Icon Sports",
    image:imgStudio("porsche","911",2024), imageVerified:true
  },
  {
    id:90, make:"Hyundai", model:"Exter", year:2024, variant:"SX(O) Turbo AMT",
    price:1043000, category:"Compact SUV", fuel:"Petrol", transmission:"AMT",
    mileage:19.4, engine:"1.2L Kappa VTVT / 1.0L Turbo", power:"83 hp", torque:"114 Nm",
    seats:5, color:"Fiery Red", rating:4.3, reviews:265,
    features:["8\" Touchscreen","Bluelink Connected","Dashcam","6 Airbags","ADAS","Sunroof"],
    pros:["Compact entry SUV","Connected tech","Unique design"],
    cons:["Underpowered on highway","Rear space tight"],
    safetyRating:4, depreciationRate:13, maintenanceCostPerYear:18000,
    insuranceCostPerYear:36000, totalCostOfOwnership5yr:1950000,
    analyticsScore:79, marketTrend:"rising", demandIndex:80,
    tag:"Entry SUV",
    image:imgStudio("hyundai","exter",2024), imageVerified:true
  }
];

const MARKET_DATA = {
  monthlySearchVolume: {
    "Compact SUV": 95000, "SUV": 85000, "Sedan": 62000,
    "Hatchback": 71000, "Electric SUV": 52000, "Luxury SUV": 28000,
    "MPV": 35000, "Luxury Sedan": 22000
  },
  priceRangeDistribution: {
    "Under 8L": 22, "8–15L": 30, "15–25L": 28, "25–50L": 13, "Above 50L": 7
  },
  fuelPreference: { "Petrol": 48, "Diesel": 18, "Electric": 22, "Hybrid": 12 },
  monthlyTrends: [
    { month:"Jan", sales:320000 }, { month:"Feb", sales:298000 }, { month:"Mar", sales:415000 },
    { month:"Apr", sales:378000 }, { month:"May", sales:392000 }, { month:"Jun", sales:441000 },
    { month:"Jul", sales:428000 }, { month:"Aug", sales:465000 }, { month:"Sep", sales:502000 },
    { month:"Oct", sales:489000 }, { month:"Nov", sales:521000 }, { month:"Dec", sales:478000 }
  ],
  topSearchedFeatures: ["Sunroof","ADAS","Wireless Charging","360 Camera","Fast Charging EV"],
  evAdoptionGrowth: 68, suvGrowth: 24, sedanDecline: -8
};

const SUBSCRIPTION_PLANS = [
  {
    id:"basic", name:"Basic", price:0, billingCycle:"Free forever", color:"#6b7280",
    features:["Browse 50 cars/month","Basic specs view","5 comparisons/month","Email support"],
    limits:{ carsPerMonth:50, comparisons:5, analytics:false, alerts:false, apiAccess:false }
  },
  {
    id:"pro", name:"Pro", price:499, billingCycle:"per month", color:"#3b82f6", popular:true,
    features:["Unlimited car browsing","Full analytics dashboard","Unlimited comparisons","Price drop alerts","Export reports (PDF)","Priority support"],
    limits:{ carsPerMonth:-1, comparisons:-1, analytics:true, alerts:true, apiAccess:false }
  },
  {
    id:"dealer", name:"Dealer", price:2999, billingCycle:"per month", color:"#f59e0b",
    features:["Everything in Pro","List up to 50 cars","Featured listings","Lead management CRM","API access","Dedicated account manager"],
    limits:{ carsPerMonth:-1, comparisons:-1, analytics:true, alerts:true, apiAccess:true }
  }
];
